name: L&S Events CI

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: install python requirements
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: build github content
      run: make github-build

    - name: deploy content as github-page
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: output
